version: '3.7'
services:
  keycloak:
    build:
      context: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    command:
      - start-dev --http-port=8109 --import-realm
    healthcheck:
      interval: 5s
      retries: 60
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8109' ]
      timeout: 2s
    ports:
      - '8109:8109'
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
  keycloak-db:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
volumes:
  keycloak-db-data: { }
