name: ci
on:
  push:
    branches:
      - develop
      - main
  pull_request_target:
    branches:
      - develop
  workflow_dispatch:
jobs:
  build-lint-test:
    runs-on: ubuntu-22.04
    name: Build, Lint and Test

    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache yarn
        uses: actions/cache@v3
        with:
          path: '.yarn/cache'
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-

      - name: Corepack
        run: |
          corepack enable
          corepack prepare

      - name: Install
        run: |
          yarn

      - name: Build
        run: |
          yarn build

      - name: Lint
        run: |
          yarn lint:ci

      - name: Start test containers
        run: |
          cd docker-oidc-adapters
          docker compose -f docker-compose.yml up -d --wait
          docker compose logs

      - name: Test
        run: |
          yarn test:ci

  release:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    needs: build-lint-test

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Git User config"
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - name: "Install Dependencies"
        run: yarn

      - name: "Build"
        run: yarn build

      - name: "Update npm"
        run: |
          npm --version
          npm install -g npm@9
          npm --version

      - name: "Semantic Release"
        run: yarn multi-semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Merge main to develop
        uses: robotology/gh-action-nightly-merge@v1.3.3
        with:
          stable_branch: 'main'
          development_branch: 'develop'
          allow_ff: true
          user_name: github-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
